# Generated by Django 5.1.7 on 2025-03-14 18:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='preferred_mode_of_attendance',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='yoe',
            new_name='prior_year_of_graduation',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='time_to_contact',
        ),
        migrations.AddField(
            model_name='alumni',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='employment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='prior_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='time_to_contact_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='time_to_contact_to',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='area_of_expertise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='PreviousContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode_of_contact', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_app.alumni')),
                ('contacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
