# Generated by Django 5.1.7 on 2025-03-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0002_rename_preferred_mode_of_attendance_alumni_availability_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['name', 'email', 'phone', 'soc_poc', 'availability', 'time_to_contact_from', 'time_to_contact_to', 'country', 'prior_course', 'prior_year_of_graduation', 'employment_status', 'company', 'area_of_expertise']},
        ),
    ]
