# Generated by Django 5.1.7 on 2025-03-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0003_alter_alumni_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={},
        ),
    ]
