# Generated by Django 5.1.7 on 2025-03-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0004_alter_alumni_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='prior_year_of_graduation',
            new_name='year_of_graduation',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='employment_status',
        ),
    ]
