# Generated by Django 5.1.7 on 2025-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0005_rename_prior_year_of_graduation_alumni_year_of_graduation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='company',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='country',
            field=models.CharField(default='UK', max_length=255, null=True),
        ),
    ]
