# Generated by Django 5.1.7 on 2025-03-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0006_alter_alumni_company_alter_alumni_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='availability',
            field=models.CharField(default='Online', max_length=50),
        ),
    ]
