# Generated by Django 5.1.7 on 2025-03-28 00:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0007_alter_alumni_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='area_of_expertise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
