# Generated by Django 5.1.7 on 2025-04-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0008_alter_alumni_area_of_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='area_of_interest',
        ),
    ]
